// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpkiRYn-NkJCyvO-y1YjKtVReNEGiIlQI',
    appId: '1:386118301041:web:2824d0726a4cda8f9a32d0',
    messagingSenderId: '386118301041',
    projectId: 'vaptest-66ecc',
    authDomain: 'vaptest-66ecc.firebaseapp.com',
    databaseURL: 'https://vaptest-66ecc-default-rtdb.firebaseio.com',
    storageBucket: 'vaptest-66ecc.appspot.com',
    measurementId: 'G-9G47T1412C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgXX0iNkVoifr7vnuESyfzqyAbL6lT3hQ',
    appId: '1:386118301041:android:255b6cba316bb2a29a32d0',
    messagingSenderId: '386118301041',
    projectId: 'vaptest-66ecc',
    databaseURL: 'https://vaptest-66ecc-default-rtdb.firebaseio.com',
    storageBucket: 'vaptest-66ecc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB87JUuoig-81eH1A-QIuBqSZyR7E1l8OA',
    appId: '1:386118301041:ios:24e7e64c42c722db9a32d0',
    messagingSenderId: '386118301041',
    projectId: 'vaptest-66ecc',
    databaseURL: 'https://vaptest-66ecc-default-rtdb.firebaseio.com',
    storageBucket: 'vaptest-66ecc.appspot.com',
    iosBundleId: 'com.vapuser.vapusuario',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB87JUuoig-81eH1A-QIuBqSZyR7E1l8OA',
    appId: '1:386118301041:ios:6396edc46fc3bbc29a32d0',
    messagingSenderId: '386118301041',
    projectId: 'vaptest-66ecc',
    databaseURL: 'https://vaptest-66ecc-default-rtdb.firebaseio.com',
    storageBucket: 'vaptest-66ecc.appspot.com',
    iosBundleId: 'com.vapuser.vapusuario.RunnerTests',
  );
}
